batch_size: 4
criterion:
  NAME: BCEAffinityPeelerLoss
dataset:
  asset_scale_std:
  - 0.0
  - 0.56
  cluster_translation_scale:
  - 0.0
  - 4.0
  max_fragments: 150
  per_asset_rotation: true
  scaling_noise_sigma: 0.001
  scene_scale:
  - 0.0
  - 0.0
  seed: 42
  translation_noise_sigma: 0.01
  translation_scale:
  - -1.0
  - 0.9
embedding_noise_sigma: 0.5
epochs: 20
grad_accum_steps: 8
lr: 0.01
lr_pct_start: 0.5
model:
  NAME: PurelyRelationalPeeler
  downsample_schedule:
  - 16
  - 16
  - 16
  - 16
  - 16
  - 16
  - 16
  - 16
  highway_dim: 64
  mlp_sizes:
  - 176
  - 176
  - 176
  - 176
  - 176
  - 176
  - 176
  - 176
  pairwise_dropout: 0.0
optimizer:
  NAME: adamw
  weight_decay: 0.035
scheduler:
  div: 10.0
  final_div_factor: 10000.0
training:
  device: cuda
  ema_alpha: 0.1
  report_interval: 100
validation:
  batch_size: 1
  threshold: 0.5
