batch_size: 4
criterion:
  NAME: FocalAffinityPeelerLoss
dataset:
  asset_scale_std:
  - 0.0
  - 0.0
  cluster_translation_scale:
  - -30.0
  - 30.0
  max_fragments: 150
  per_asset_rotation: true
  scaling_noise_sigma: 0.0
  scene_scale:
  - 0.0
  - 0.0
  seed: 42
  translation_noise_sigma: 0.0
  translation_scale:
  - 0.0
  - 0.0
embedding_noise_sigma: 0.0
epochs: 20
grad_accum_steps: 8
lr: 0.003
lr_pct_start: 0.1
model:
  NAME: PurelyRelationalPeeler
  downsample_schedule:
  - 16
  - 16
  highway_dim: 16
  mlp_sizes:
  - 64
  - 64
  pairwise_dropout: 0.0
optimizer:
  NAME: adamw
  weight_decay: 0.035
scheduler:
  div: 100.0
  final_div_factor: 10.0
training:
  device: cuda
  ema_alpha: 0.1
  report_interval: 100
validation:
  batch_size: 1
  threshold: 0.5
