model:
  NAME: PointNextMAE
  decoder_hidden_dim: 512
  decoder_points: 1024
  encoder_args:
    NAME: PointNextEncoder
    act_args:
      act: relu
    aggr_args:
      feature_type: dp_fj
      reduction: max
    blocks:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    conv_args:
      order: conv-norm-act
    expansion: 4
    group_args:
      NAME: ballquery
      normalize_dp: true
    in_channels: 4
    norm_args:
      norm: bn
    nsample: 32
    radius: 0.15
    radius_scaling: 1.5
    sa_layers: 2
    sa_use_res: true
    strides:
    - 1
    - 2
    - 2
    - 2
    - 2
    - 1
    width: 32
  jitter_prob: 0.9
  jitter_sigma: 0.01
  latent_dim: 256
training:
  batch_size: 512
  channels:
    combined: true
    normal: false
    surface: false
  device: cuda
  epochs: 201
  lr: 0.0013
  num_points: 1024
  report_interval: 10
  warmup_epochs: 1
